/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 gaming_setup.glb -T 
Files: gaming_setup.glb [10.45MB] > /Users/shajimohammed/Desktop/BCS/Projects/portfolio/public/models/gaming_setup-transformed.glb [848.38KB] (92%)
Author: DeadLink (https://sketchfab.com/d43dLink)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/gaming-setup-8a75c64542c14be0ad3dcf75423eda0d
Title: Gaming Setup
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Computer(props) {
  const { nodes, materials } = useGLTF("/models/gaming_setup-transformed.glb");
  return (
    <group rotation={[0, Math.PI / 2.8, 0]} {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Stoo1_Stoo1_0.geometry}
        material={materials.Stoo1}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.sit_sit_0.geometry}
        material={materials.material}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pc_pc_0.geometry}
        material={materials.material_2}
        scale={0.01}
      />
    </group>
  );
}

useGLTF.preload("/models/gaming_setup-transformed.glb");
